#!/bin/sh

if [ ! -f /NERFSTUDIO/gluemap_checkpoints/done.txt ]; then
  echo "Please run zx_gluemap_setup first to download models. ( or create /NERFSTUDIO/gluemap_checkpoints/done.txt to bypass this message. )"
  exit
fi

/opt/gluemap-env/bin/gluemap-demo "$@"
