#!/bin/sh
mkdir -p $2
ns-train splatfacto --output-dir $(realpath $2) \
    --pipeline.model.use_bilateral_grid True \
    --pipeline.model.sh-degree 2 \
    --pipeline.model.use-scale-regularization True \
    --pipeline.model.num-downscales 0 \
    --data $(realpath $1) colmap \
        --downscale-factor 1