#!/usr/bin/python3
import cv2
import numpy as np
import glob
import time
import piexif
import sys

#args needed: dataset
#args needed: checkerboard size WxH
#side length (metres)


if len(sys.argv) < 4:
    print("Simple OpenCV Camera calibrator!")
    print()
    print("How get a dataset: ")
    print("1. Print a sharp black & white checkerboard grid of squares, with a different number of rows and columns (10x8 is a good number, for example)")
    print("2. Glue it or tape it onto a flat surface to be really perfectly flat. Distortions will cause bad calibration!")
    print("3. Switch your camera to a manual focus/disable autofocus, and pick a good distance from the checkerboard.")
    print("4. Get a dataset of 24-32 sharp images, ensuring that the whole rectange is in frame. Capture the grid on all parts of the camera FOV, at many angles and distances. ")
    print("   |-- res of 1080p or higher is ideal.")
    print("5. Measure the side length of one checkerboard tile in meters, to 0.1mm (0.001) accuracy or better. Don't lose this value!")
    print("")
    print("")
    print("Creating camera intrinsics: ")
    print("Run this utility in this format (all image formats are accepted!)")
    print("$ zx_calibrate my_dataset/*.jpg 10x8 0.0211")
    print("where: [dataset selector] [grid rows x columns] [side length in meters]")
    print("")
    print("After processing completes, check for any images with a high reprojection error, and delete them from the dataset.")
    print("Rerun this refining process until you reach a good error value (sub 1px error should be achievable!)")
    
    sys.exit()

CHECKERBOARD = tuple(map(lambda x: int(x) - 1, sys.argv[2].split("x"))) #mine: inner corners = (11,7)
SQUARE_SIZE = float(sys.argv[3]) #mine: 0.0211 meters

criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 1001, 1e-7)

objp = np.zeros((CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32)
objp[:, :2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
objp = objp * SQUARE_SIZE

objpoints = []
imgpoints = []

images = glob.glob(sys.argv[1])

camera = ""
maker = ""

for filename in images:
    if camera == "":
        try:
            exif_dict = piexif.load(filename)
            print(exif_dict["0th"])
            camera = exif_dict["0th"][272].decode("utf-8").replace("PIX4Dcatch.", "")
            maker = exif_dict["0th"][271].decode("utf-8")
        except:
            camera = "unknown"
            maker = "unknown"
    img = cv2.imread(filename)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, None)

    if ret:
        objpoints.append(objp)

        corners2 = cv2.cornerSubPix(gray, corners, (21, 21), (-1, -1), criteria)
        imgpoints.append(corners2)

ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(
    objpoints, imgpoints, gray.shape[::-1], None, None, flags=cv2.CALIB_FIX_K3
)

print("Reprojection errors...")
time.sleep(1)
for i in range(len(objpoints)):
    imgpoints2, _ = cv2.projectPoints(objp, rvecs[i], tvecs[i], mtx, dist)
    error = cv2.norm(imgpoints[i], imgpoints2, cv2.NORM_L2) / len(imgpoints2)
    print(f"{images[i]} - {error}px")
    
print("^ remove images with high error values")
print()

cmap_text = ",".join(map(lambda x: str(x), [
    mtx[0,0], #f_x
    mtx[1,1], #f_y
    mtx[0,2], #c_x
    mtx[1,2], #c_y
    dist[0,0], #k_1
    dist[0,1], #k_2
    dist[0,2], #p_1
    dist[0,3], #p_2
])) + f"\n{camera},{maker}\n"
print(f"COLMAP string: {cmap_text}")
fname = f"{camera}_{time.asctime().replace("  ", " ").replace(" ", "_").replace(":", "-")}.cv2_calib.csv"
print(f"Saving calibration data to {fname}")
with open(fname, mode="w") as f:
    f.write(cmap_text)