#!/bin/sh
mkdir -p /NERFSTUDIO/weights
cd /NERFSTUDIO/weights

echo "Usage: $0 <small|medium|large|aliked|loma_base|loma_large|sift_matchers>"
SZ=${1:-"small"}

if [ "$SZ" = "aliked" ]; then
    echo "Downloading ALIKED ONNX models and vocabtrees..."
    sleep 1
    wget https://github.com/colmap/colmap/releases/download/3.13.0/aliked-n32.onnx
    wget https://github.com/colmap/colmap/releases/download/3.13.0/aliked-n16rot.onnx
    wget https://github.com/colmap/colmap/releases/download/3.13.0/aliked-lightglue.onnx
    wget https://github.com/colmap/colmap/releases/download/3.13.0/vocab_tree_faiss_flickr100K_words64K_aliked_n16rot.bin
    wget https://github.com/colmap/colmap/releases/download/3.13.0/vocab_tree_faiss_flickr100K_words64K_aliked_n32.bin
if [ "$SZ" = "sift_matchers" ]; then
    echo "Downloading SIFT ONNX matcher models..."
    sleep 1
    wget https://github.com/colmap/colmap/releases/download/3.13.0/sift-lightglue.onnx
    wget https://github.com/colmap/colmap/releases/download/3.13.0/bruteforce-matcher.onnx
if [ "$SZ" = "loma_base" ]; then
    echo "Downloading LoMa-B ONNX models and vocabtrees..."
    sleep 1
    wget https://github.com/davnords/storage/releases/download/loma/loma_detector.onnx
    wget https://github.com/davnords/storage/releases/download/loma/loma_descriptor_dedode_b.onnx
    wget https://github.com/davnords/storage/releases/download/loma/loma_matcher_B.onnx
    wget https://github.com/davnords/storage/releases/download/loma/vocab_tree_loma_b_flickr100k.bin
if [ "$SZ" = "loma_large" ]; then
    echo "Downloading LoMa-L ONNX models and vocabtrees..."
    sleep 1
    wget https://github.com/davnords/storage/releases/download/loma/loma_detector.onnx
    wget https://github.com/davnords/storage/releases/download/loma/loma_descriptor_dedode_b.onnx
    wget https://github.com/davnords/storage/releases/download/loma/loma_matcher_L.onnx
    wget https://github.com/davnords/storage/releases/download/loma/vocab_tree_loma_b_flickr100k.bin
elif [ "$SZ" = "large" ]; then
    echo "Warning: the large vocab tree is 275MB! Proceeding in 3 seconds..."
    sleep 3
    wget https://github.com/colmap/colmap/releases/download/3.11.1/vocab_tree_faiss_flickr100K_words32K.bin
    wget https://github.com/colmap/colmap/releases/download/3.11.1/vocab_tree_faiss_flickr100K_words256K.bin
    wget https://github.com/colmap/colmap/releases/download/3.11.1/vocab_tree_faiss_flickr100K_words1M.bin
elif [ "$SZ" = "medium" ]; then
    echo "Downloading small + medium vocab trees!"
    wget https://github.com/colmap/colmap/releases/download/3.11.1/vocab_tree_faiss_flickr100K_words32K.bin
    wget https://github.com/colmap/colmap/releases/download/3.11.1/vocab_tree_faiss_flickr100K_words256K.bin
else
    echo "Downloading small vocab tree..."
    wget https://github.com/colmap/colmap/releases/download/3.11.1/vocab_tree_faiss_flickr100K_words32K.bin
fi
