#!/usr/bin/python3

# TODO: Add options for explicit camera intrinsics
# - intrinsics for pose prior mapper
# - intrinsics for AR pipeline
# - intrinsics for GLOMAP
# -  disable intrinsic+focalpoint optimisation on all bundle ajdustment stages/mapper pilelines if predefined camera intrinsics
# - if possible, pass intrinsics to gluemap-demo
# ^done mostlys

import time
import sys

times = []
recent_time = time.time()
init_time = recent_time


def profilerStage(stage):
    global times
    global recent_time
    stage_time = time.time()
    times.append({"name": stage, "time": stage_time - recent_time, "stamp": stage_time})
    recent_time = stage_time
    sys.stdout.flush()
    sys.stderr.flush()


import pathlib
import os
import json
import csv
import subprocess
import math
import random
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor
import numpy as np
from scipy.spatial.transform import Rotation as R
from tqdm import tqdm
import cv2

EXPERIMENTAL_GLOMAP = False

EXPERIMENTAL_ONNX_CFG = None
ONNX_SETUPDB = {}

EXPERIMENTAL_NOBLUR = False
EXPERIMENTAL_IMFILTER = False
EXPERIMENTAL_BETTERSIFT = False
STAGE_VOCABTREE = False
STAGE_VOCABTREE_DEPTH = 50
STAGE_SPATIAL_RADIUS = 6
STAGE_DOWNSCALE = -1
AR_MAX_REPROJECTION_ERROR = 12.0
EXPERIMENTAL_SOLVER_BACKEND = "CERES"
EXPERIMENTAL_AR = False
EXPERIMENTAL_AR_ITERS = 4
EXPERIMENTAL_DENOISE = False
EXPERIMENTAL_DENOISE_STRENGTH = 10
EXPERIMENTAL_NOBLUR_THRESH = 18000
SOLVER_ITERATION_CAP = 200
EXPERIMENTAL_GLUE = False
HAS_CUSTOM_INTRINSICS = False
CUSTOM_INTRINSICS = ""


def registerOnnxModel(easyName: str, profile: dict):
    ONNX_SETUPDB[easyName] = profile
    prereqs = []
    for k in profile.keys():
        v = profile[k]
        t = type(v)
        if t == str:
            if v.startswith("/"):
                profile[k] = "/NERFSTUDIO/weights" + v
                prereqs.append(profile[k])
        if t == list:
            newList = []
            for i in v:
                if i.startswith("/"):
                    newList.append("/NERFSTUDIO/weights" + i)
                    prereqs.append(newList[-1])
                else:
                    newList.append(i)
            profile[k] = newList
    profile["prereqs"] = prereqs
    print(f"Registered ONNX feature model: {easyName}")


registerOnnxModel(
    "onnx",
    {
        "downloadProfile": "aliked",  # profile name to pass to zx_download_assets
        "vocabTree": "/vocab_tree_faiss_flickr100K_words64K_aliked_n16rot.bin",  # filename of vocab tree
        "extractionType": "ALIKED_N16ROT",
        "extractionOptions": [
            "--AlikedExtraction.n16rot_model_path",
            "/aliked-n16rot.onnx",
        ],
        "matcherType": "ALIKED_LIGHTGLUE",
        "matcherOptions": [
            "--AlikedMatching.lightglue_model_path",
            "/aliked-lightglue.onnx",
        ],
    },
)

registerOnnxModel(
    "loma_base",
    {
        "downloadProfile": "loma_base",
        "vocabTree": "/vocab_tree_loma_b_flickr100k.bin",
        "extractionType": "LOMA_B",
        "extractionOptions": [
            "--LomaExtraction.detector_model_path",
            "/loma_detector.onnx",
            "--LomaExtraction.descriptor_model_path",
            "/loma_descriptor_dedode_b.onnx",
        ],
        "matcherType": "LOMA_B",
        "matcherOptions": ["--LomaMatching.b_model_path", "/loma_matcher_B.onnx"],
    },
)

registerOnnxModel(
    "loma_large",
    {
        "downloadProfile": "loma_large",
        "vocabTree": "/vocab_tree_loma_b_flickr100k.bin",
        "extractionType": "LOMA_B",
        "extractorOptions": [
            "--LomaExtraction.detector_model_path",
            "/loma_detector.onnx",
            "--LomaExtraction.descriptor_model_path",
            "/loma_descriptor_dedode_b.onnx",
        ],
        "matcherType": "LOMA_L",
        "matcherOptions": ["--LomaMatching.l_model_path", "/loma_matcher_L.onnx"],
    },
)

profilerStage("Runtime Setup")


def quietRun(args, check=False):
    subprocess.run(
        args, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=check
    )


if len(sys.argv) < 3:
    print(
        "Usage: zx_process_pix4d <path/to/pix4d_raw_exported.zip> <path/to/dest> [global,noblur=18000,onnx=aliked,ar=4,solver=200]\n",
        file=sys.stderr,
    )
    print(
        "Example: zx_process_pix4d vid/simple_demo_pix4d.zip experiment/ global\n"
        + "Example: zx_process_pix4d vid/simple_demo_pix4d.zip experiment/ noblur=18000,global\n"
        + "Example: zx_process_pix4d vid/simple_demo_pix4d.zip experiment/\n"
        + "Example: zx_process_pix4d vid/simple_demo_pix4d.zip experiment/ ar=4,noblur,solver=300\n",
        file=sys.stderr,
    )
    print(
        "Built for pix4Dcatch v1.30.0, using a no-account patch and not using RTK\n",
        file=sys.stderr,
    )
    print(
        "Extraflags: \n"
        + "  global: Use GLOBAL_MAPPER mapping algorithm, which is much faster than POSE_MAPPER, but may be less accurate\n"
        + "  noblur=18000: Filter images by laplacian variance, to remove blurred images.\n"
        + f"  onnx={"|".join(ONNX_SETUPDB.keys())}: Use an ONNX model for feature extraction and matching instead of SIFT, which does better on less-detailed surfaces and provides higher accuracy. Requires 'zx_download_assets <modelname>' to run.\n"
        + "  ar=4: Skip the mapping stage entirely, and instead use AR positions and refine those. Value is equal to the number of adjustment and retriangulation iterations. recommended to use in combination with raising the Ceres/Caspar solver iteration cap. Incompatible with ONNX features, as it needs actual points.\n"
        + "  solver=200: Maximum number of solver iterations for the Ceres / Caspar GPU solvers\n"
        + "  caspar: Use Capsar solver instead of Ceres, for full GPU acceleration.\n"
        + "  vocab=50: Add a vocab tree matching stage, where the value is equal to the number of match candidates per image.\n"
        + "  spatial=6: Use this flag to modify the radius of the spatial matching stage.\n"
        + "  imfilter: (for AR pipeline) enable image filtering to remove bad cameras.\n"
        + "  bettersift: (for non-ONNX pipelines) enables SIFT Affine Shape Estimation and Domain Size Pooling, improving accuracy. This makes feature extraction use the CPU instead, making it slower.\n"
        + "  denoise=10: Uses OpenCV2 Non-Local Means denoising, with a default denoising strength of 10\n"
        + "  downscale=720: Downscales (area average) to the specified pixel height, after any denoising stages. Recommended to set to 540 or lower for GLUEMAP\n"
        + "  glue: Uses the highly experimental GLUEMAP backend for feedforward 3D processing. Expect crashes."
        + "  intrinsics=file.cv2_calib.csv: uses given intrinsics and disables intrinsic refinement to improve solution accuracy. Does not work on Caspar backend. Get them using zx_calibrate",
        file=sys.stderr,
    )
    sys.exit(1)

zip_path = str(Path(sys.argv[1]).absolute())
if not Path(sys.argv[1]).is_file():
    print(f"Bad zip path: {zip_path}")
    sys.exit(1)

quietRun(["sh", "-c", "rm -rf /fast/*"])
quietRun(["mkdir", "-p", "/fast"])

true_dest_path = str(Path(sys.argv[2]).absolute())
dest_path = "/fast" + str(Path(sys.argv[2]).absolute())

quietRun(["rm", "-r", dest_path])

quietRun(["mkdir", "-p", dest_path])

print(f"Using fast temp-dir: {dest_path}")
print(f"Will finalise to: {true_dest_path}")

if len(sys.argv) > 3:
    flags = sys.argv[3].lower().strip().split(",")
    if "global" in flags:
        EXPERIMENTAL_GLOMAP = True
        print("Enabling GLOBAL_MAPPER mapper")
    if "glue" in flags:
        EXPERIMENTAL_GLUE = True
        print("Switching pipeline from COLMAP to GLUEMAP")
    if "caspar" in flags:
        EXPERIMENTAL_SOLVER_BACKEND = "CASPAR"
        print("Switching to Caspar solver backend")
    if "imfilter" in flags:
        EXPERIMENTAL_IMFILTER = True
        print("Enabling image filtering for AR pipeline")
    if "bettersift" in flags:
        EXPERIMENTAL_BETTERSIFT = True
        print("Enabling extended SIFT capabilities")
    for flag in flags:
        if flag.startswith("noblur"):
            EXPERIMENTAL_NOBLUR = True
            if flag.startswith("noblur="):
                EXPERIMENTAL_NOBLUR_THRESH = int(flag.replace("noblur=", ""))
                print(
                    f"Enabling blur detection with custom threshold of lv={EXPERIMENTAL_NOBLUR_THRESH}"
                )
            else:
                print(
                    f"Enabling blur detection with default threshold of lv={EXPERIMENTAL_NOBLUR_THRESH}"
                )
        if flag.startswith("ar"):
            EXPERIMENTAL_AR = True
            if flag.startswith("ar="):
                EXPERIMENTAL_AR_ITERS = int(flag.replace("ar=", ""))
            print(f"Using AR priors, with {EXPERIMENTAL_AR_ITERS} iterations")
            print(
                f"Note: if your position data is noisy, try switching from the experimental AR pipeline to GLOBAL"
            )
        if flag.startswith("intrinsics="):
            HAS_CUSTOM_INTRINSICS = True
            intrinsics_data = []
            with open(flag.replace("intrinsics=", "").strip()) as f:
                intrinsics_data = f.readlines()
            CUSTOM_INTRINSICS = intrinsics_data[0].strip()
            print(f"Using custom camera intrinsics: {CUSTOM_INTRINSICS}")
            maker = intrinsics_data[1].split(",")[1]
            model = intrinsics_data[1].split(",")[0]
            print(f"Camera model: {model} by {maker}")
        if flag.startswith("denoise"):
            EXPERIMENTAL_DENOISE = True
            if flag.startswith("denoise="):
                EXPERIMENTAL_DENOISE_STRENGTH = int(flag.replace("denoise=", ""))
            print(
                f"Enabling NLMeans denoising, strength={EXPERIMENTAL_DENOISE_STRENGTH}"
            )
            print(
                f"Note: Only use this when you have high ISO noise (eg: night dataset)"
            )
        if flag.startswith("downscale"):
            STAGE_DOWNSCALE = 720
            if flag.startswith("downscale="):
                STAGE_DOWNSCALE = int(flag.replace("downscale=", ""))
            print(f"Enabling downscaling to {STAGE_DOWNSCALE}p")
            print(f"Note: Will not affect images used in Nerfstudio!")
        if flag.startswith("vocab"):
            STAGE_VOCABTREE = True
            if flag.startswith("vocab="):
                STAGE_VOCABTREE_DEPTH = int(flag.replace("vocab=", ""))
            print(
                f"Enabling vocab-tree stage, with {STAGE_VOCABTREE_DEPTH} match candidates per image."
            )
        if flag.startswith("onnx="):
            model_id = flag.replace("onnx=", "").lower()
            if not model_id in ONNX_SETUPDB:
                print(
                    f"ONNX model {model_id} does not exist! Possible values: {', '.join(ONNX_SETUPDB.keys())}"
                )
                sys.exit(1)
            EXPERIMENTAL_ONNX_CFG = ONNX_SETUPDB[model_id]
            print(f"Enabling ONNX model: {EXPERIMENTAL_ONNX_CFG['downloadProfile']}")
        if flag.startswith("solver="):
            SOLVER_ITERATION_CAP = int(flag.replace("solver=", ""))
            print(f"Setting solver iteration cap to {SOLVER_ITERATION_CAP}")
        if flag.startswith("spatial="):
            STAGE_SPATIAL_RADIUS = int(flag.replace("spatial=", ""))
            print(f"Setting spatial matching radius to {STAGE_SPATIAL_RADIUS}")

if HAS_CUSTOM_INTRINSICS and (EXPERIMENTAL_SOLVER_BACKEND == "CASPAR"):
    print(
        "Caspar does not support the OPENCV camera model, so your custom intrinsics can not be used."
    )
    sys.exit()

if EXPERIMENTAL_AR and ((EXPERIMENTAL_ONNX_CFG != None) or EXPERIMENTAL_BETTERSIFT):
    print(
        "ONNX/BETTER SIFT features cannot be used with point_triangulator, and as such don't work on the AR pipeline!"
    )
    sys.exit(1)

if EXPERIMENTAL_ONNX_CFG != None:
    for prereq in EXPERIMENTAL_ONNX_CFG["prereqs"]:
        if not Path(prereq).is_file():
            print(f"Error: {prereq} was not found!!!")
            print(
                f" - 'zx_download_assets {EXPERIMENTAL_ONNX_CFG["downloadProfile"]}' should resolve this."
            )
            sys.exit(1)

VOCAB_TREE_PATH = (
    EXPERIMENTAL_ONNX_CFG["vocabTree"]
    if EXPERIMENTAL_ONNX_CFG != None
    else "/NERFSTUDIO/weights/vocab_tree_faiss_flickr100K_words256K.bin"
)

if STAGE_VOCABTREE:
    if not Path(VOCAB_TREE_PATH).is_file():
        if EXPERIMENTAL_ONNX_CFG != None:
            print(
                f"Error: {EXPERIMENTAL_ONNX_CFG["extractionType"]} vocab-trees not found. Run 'zx_download_assets {EXPERIMENTAL_ONNX_CFG["downloadProfile"]}' to download them."
            )
        else:
            print(
                "Error: SIFT vocab-trees not found. Run 'zx_download_assets medium' to download them."
            )
        sys.exit(1)


def pfile(strPath):
    return dest_path + "/" + strPath


start_time = time.time()

print("Clearing previous directory...")
quietRun(["rm", "-r", true_dest_path])

profilerStage("Init")

time.sleep(0.1)

print("Extracting pix4d data...")
quietRun(
    [
        "unzip",
        "-q",
        zip_path,
        "-d",
        dest_path,
        "-x",
        "*Confidence_*",
        "-x",
        "*DepthMap_*",
    ]
)

time.sleep(1)
os.sync()
time.sleep(1)

subdir = str([x for x in Path(dest_path).absolute().iterdir() if x.is_dir()][0])
print(f"Using directory: {subdir}")
quietRun(["mv", subdir, dest_path + "/pixdata"])

profilerStage("Extraction")

projectMeta = None
with open(pfile("pixdata/projectMetadata.json"), "r") as f:
    projectMeta = json.load(f)

if projectMeta["locationInformation"]["coordinateSystem"]["name"] != "WGS 84":
    print("Expected WGS 84 coordinate system!")
    sys.exit(1)

AR_positionData = {}
xy_accuracy = 0
z_accuracy = 0

useCorrectedData = False

with open(pfile("pixdata/_gps/_locations_gps_ar_corrected.csv"), "r") as f:
    if len(f.readlines()) > 2:
        useCorrectedData = True
        print(
            "Your capture contains error-corrected data, using that instead of raw AR"
        )

with open(
    pfile(
        "pixdata/_gps/_locations_gps_ar_corrected.csv"
        if useCorrectedData
        else "pixdata/_gps/_all_locations.csv"
    ),
    "r",
) as f:  # pixdata/_gps/_all_locations.csv
    reader = csv.reader(f)

    header = next(reader)

    IDX_IMAGE = header.index("image")
    IDX_ROLL = header.index("roll")
    IDX_PITCH = header.index("pitch")
    IDX_YAW = header.index("yaw")
    IDX_LAT = header.index("latitude")
    IDX_LON = header.index("longitude")
    IDX_ALT = header.index("altitude")
    IDX_XY = header.index("xyAccuracy")
    IDX_Z = header.index("zAccuracy")

    if not useCorrectedData:
        marker = []
        while not (len(marker) == 1 and marker[0].lower().endswith("ar")):
            marker = next(reader)

    for row in reader:
        if row[0].strip().startswith("//"):
            break

        img_name = row[IDX_IMAGE]

        if EXPERIMENTAL_DENOISE or (STAGE_DOWNSCALE != -1):
            img_name = ".".join(os.path.basename(img_name).split(".")[:-1]) + ".png"

        AR_positionData[img_name] = {
            "roll": float(row[IDX_ROLL]),
            "pitch": float(row[IDX_PITCH]),
            "yaw": float(row[IDX_YAW]),
            "latitude": float(row[IDX_LAT]),
            "longitude": float(row[IDX_LON]),
            "altitude": float(row[IDX_ALT]),
            "img": img_name,
        }
        xy_accuracy = max(xy_accuracy, float(row[IDX_XY]))
        z_accuracy = max(z_accuracy, float(row[IDX_Z]))

profilerStage("Parsing")

images_dir = pfile("images/")

quietRun(["mkdir", "-p", images_dir])

print("Moving frames...")
quietRun(["sh", "-c", f"mv {pfile("pixdata/Image_*")} {images_dir}"])

profilerStage("Frame Copy")


def process_blur_batch(batch_paths, threshold):
    if not batch_paths:
        return []

    cmd = ["zx_find_blurry.py", str(threshold)] + [str(p) for p in batch_paths]

    result = subprocess.run(cmd, capture_output=True, text=True, check=True)
    return [
        line for line in result.stdout.replace(" ", "\n").splitlines() if line.strip()
    ]


if EXPERIMENTAL_NOBLUR:
    parallel = os.cpu_count() - 2
    with ProcessPoolExecutor(max_workers=parallel) as executor:
        root = images_dir
        images = [str(img) for img in Path(root).iterdir() if img.is_file()]
        images.sort()
        print(
            f"Scanning a total of {len(images)} frames for blurring with thresh={EXPERIMENTAL_NOBLUR_THRESH}"
        )
        arg_list = [[[], EXPERIMENTAL_NOBLUR_THRESH] for _ in range(parallel)]
        allocator = 0
        for path in images:
            arg_list[allocator][0].append(path)
            allocator = (allocator + 1) % parallel

        futures = [executor.submit(process_blur_batch, *args) for args in arg_list]
        results = [future.result() for future in futures]
        blurry_count = 0
        for result in results:
            blurry_count += len(result)

        print(
            f"Found that {int(blurry_count / len(images) * 100)}% frames were blurry ({blurry_count} frames)"
        )
        if blurry_count >= len(images) / 2:
            print("Walk slower, or change the blurriness threshold.")
            time.sleep(1)
        if blurry_count >= len(images):
            print("Change the blurriness threshold!")
            exit(1)
        subprocess.run(["zx_find_blurry.py", "-1", images[0]])
        print("Purging blurry frames...")
        flattenedList = []
        for result in results:
            for file in result:
                flattenedList.append(file.strip())
        flattenedList.sort()
        quietRun(["rm"] + flattenedList)
    profilerStage("NoBlur")

if EXPERIMENTAL_DENOISE or (STAGE_DOWNSCALE != -1):
    import piexif

    in_dir = images_dir
    out_dir = pfile("prepped/")

    os.makedirs(in_dir, exist_ok=True)
    os.makedirs(out_dir, exist_ok=True)

    images = [
        f for f in os.listdir(in_dir) if f.lower().endswith((".png", ".jpg", ".jpeg"))
    ]

    print(f"Preprocessing {len(images)} images...")
    from PIL import Image

    for filename in tqdm(images, desc="Capture Dataset"):
        input_path = os.path.join(in_dir, filename)
        base_name = os.path.splitext(filename)[0]
        output_path = os.path.join(out_dir, f"{base_name}.png")
        search_window = 21
        block_size = 7
        img = cv2.imread(input_path)
        h, w = img.shape[:2]
        exif_bytes = None

        try:
            exif_dict = piexif.load(input_path)
            if exif_dict:
                exif_bytes = piexif.dump(exif_dict)
        except Exception as e:
            pass

        if EXPERIMENTAL_DENOISE:
            img = cv2.fastNlMeansDenoisingColored(
                src=img,
                dst=None,
                h=EXPERIMENTAL_DENOISE_STRENGTH,
                hColor=EXPERIMENTAL_DENOISE_STRENGTH,
                templateWindowSize=block_size,
                searchWindowSize=search_window,
            )
        if STAGE_DOWNSCALE != -1 and h > STAGE_DOWNSCALE:
            aspect_ratio = w / h
            new_width = int(STAGE_DOWNSCALE * aspect_ratio)
            img = cv2.resize(
                img, (new_width, STAGE_DOWNSCALE), interpolation=cv2.INTER_AREA
            )

        rgb_data = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        pil_img = Image.fromarray(rgb_data)

        if exif_dict:
            if "0th" in exif_dict:
                exif_dict["0th"][piexif.ImageIFD.ImageWidth] = w
                exif_dict["0th"][piexif.ImageIFD.ImageLength] = h
            if "Exif" in exif_dict:
                exif_dict["Exif"][piexif.ExifIFD.PixelXDimension] = w
                exif_dict["Exif"][piexif.ExifIFD.PixelYDimension] = h

            exif_bytes = piexif.dump(exif_dict)
            pil_img.save(output_path, format="PNG", exif=exif_bytes)
        else:
            pil_img.save(output_path, format="PNG")
    profilerStage("Denoising & Downscaling")
    images_dir = out_dir

print(f"COLMAP Image Directory: {images_dir}")

print("Preparing COLMAP workspace and spatial priors...")
quietRun(["mkdir", "-p", pfile("colmap")])
quietRun(["mkdir", "-p", pfile("colmap/sparse/0")])

db_path = pfile("colmap/database.db")
priors_file = pfile("colmap/spatial_priors.txt")

first_img = list(AR_positionData.keys())[0]
ref_lat = AR_positionData[first_img]["latitude"]
ref_lon = AR_positionData[first_img]["longitude"]
ref_alt = AR_positionData[first_img]["altitude"]

R_a = 6378137.0
with open(priors_file, "w") as pf:
    for img_name, data in AR_positionData.items():
        if not Path(images_dir + data["img"]).is_file():
            # print(images_dir + data["img"])
            continue
        dlat = math.radians(data["latitude"] - ref_lat)
        dlon = math.radians(data["longitude"] - ref_lon)
        x = dlon * R_a * math.cos(math.radians(ref_lat))
        y = dlat * R_a
        z = data["altitude"] - ref_alt
        roll = data["roll"]
        pitch = data["pitch"]
        yaw = data["yaw"]
        pf.write(f"{img_name} {x} {y} {z}\n")

if EXPERIMENTAL_AR:
    with open(pfile("colmap/sparse/0/images.txt"), "w") as img:
        frame_index = 1
        for img_name, data in AR_positionData.items():
            if not Path(images_dir + data["img"]).is_file():
                continue
            dlat = math.radians(data["latitude"] - ref_lat)
            dlon = math.radians(data["longitude"] - ref_lon)
            x = dlon * R_a * math.cos(math.radians(ref_lat))
            y = dlat * R_a
            z = data["altitude"] - ref_alt
            camera_center = np.array([x, y, z], dtype=np.float64)
            yaw = math.radians(data["yaw"])
            pitch = math.radians(data["pitch"])
            roll = math.radians(data["roll"])
            r_yaw = R.from_rotvec([0, 0, -yaw])
            r_pitch = R.from_rotvec([pitch, 0, 0])
            r_roll = R.from_rotvec([0, roll, 0])
            r_device_to_world = r_yaw * r_pitch * r_roll
            R_body_to_colmap_cam = np.array([[1, 0, 0], [0, -1, 0], [0, 0, -1]])
            r_body_to_colmap = R.from_matrix(R_body_to_colmap_cam)
            r_colmap_cam_to_world = r_device_to_world * r_body_to_colmap
            r_world_to_colmap = r_colmap_cam_to_world.inv()
            R_mat = r_world_to_colmap.as_matrix()
            tvec = -R_mat @ camera_center
            q = r_world_to_colmap.as_quat()
            qx, qy, qz, qw = q[0], q[1], q[2], q[3]
            img.write(
                f"{frame_index} {qw} {qx} {qy} {qz} {tvec[0]} {tvec[1]} {tvec[2]} 1 {img_name}\n\n"
            )
            frame_index += 1

profilerStage("Creating Priors")

time.sleep(3)

if EXPERIMENTAL_GLUE:  # 3D feedforward
    if not Path("/NERFSTUDIO/gluemap_checkpoints/dino_salad.ckpt").is_file():
        print(
            "You do not have the necessary checkpoint and tensor files needed in order to run GLUEMAP."
        )
        print(
            "Please run 'zx_gluemap_setup' or manually place the following files in /NERFSTUDIO/gluemap_checkpoints/:"
        )
        print(" - pi3.safetensors")
        print(" - dino_salad.ckpt")
        print(" - vggsfm_v2_0_0_track_predictor.bin")
        print(" - checkpoint-dg+visym.pth")
        sys.exit(1)

    print("Launching GLUEMAP...")
    if random.randint(0, 24) > 23:
        print("Glue!")
    subprocess.run(
        [
            "gluemap-demo",
            "--images_path",
            images_dir,
            "--write_path",
            pfile("colmap/sparse"),
            "--intrinsics_mode",
            "SHARED",
            "--camera_model",
            "OPENCV",
            "--chosen_model",
            "pi3",
            "--path_feedforward",
            "/NERFSTUDIO/gluemap_checkpoints/pi3.safetensors",
            "--path_retrieval",
            "/NERFSTUDIO/gluemap_checkpoints/dino_salad.ckpt",
            "--path_tracker",
            "/NERFSTUDIO/gluemap_checkpoints/vggsfm_v2_0_0_track_predictor.bin",
            "--path_dg",
            "/NERFSTUDIO/gluemap_checkpoints/checkpoint-dg+visym.pth",
            "--subfolder_regex",
            '".*"',
            "--is_sequential",
        ]
    )
    profilerStage("GLUEMAP")
else:  # standard COLMAP
    extraExtractionFlags = []
    extraMatchingFlags = ["--FeatureMatching.guided_matching", "1"]
    if EXPERIMENTAL_ONNX_CFG != None:
        extraExtractionFlags += [
            "--FeatureExtraction.type",
            EXPERIMENTAL_ONNX_CFG["extractionType"],
        ] + EXPERIMENTAL_ONNX_CFG["extractionOptions"]

        extraMatchingFlags = [
            "--FeatureMatching.type",
            EXPERIMENTAL_ONNX_CFG["matcherType"],
        ] + EXPERIMENTAL_ONNX_CFG["matcherOptions"]

    elif EXPERIMENTAL_BETTERSIFT:
        extraExtractionFlags += [
            "--SiftExtraction.estimate_affine_shape",
            "1",
            "--SiftExtraction.domain_size_pooling",
            "1",
        ]
    if HAS_CUSTOM_INTRINSICS:
        extraExtractionFlags += [
            "--ImageReader.camera_params",
            CUSTOM_INTRINSICS,
        ]

    print("Step 1: Extracting features...")

    subprocess.run(
        [
            "colmap",
            "feature_extractor",
            "--database_path",
            db_path,
            "--image_path",
            images_dir,
            "--ImageReader.single_camera",
            "1",
            "--ImageReader.camera_model",
            "OPENCV" if EXPERIMENTAL_SOLVER_BACKEND == "CERES" else "SIMPLE_RADIAL",
            "--FeatureExtraction.use_gpu",
            "1",
            "--SiftExtraction.max_num_features",
            "8192",
            "--FeatureExtraction.num_threads",
            "-1",
        ]
        + extraExtractionFlags
    )

    profilerStage("Feature Extraction")

    print("Step 2a: Sequential matching...")
    subprocess.run(
        [
            "colmap",
            "sequential_matcher",
            "--database_path",
            db_path,
            "--SequentialMatching.overlap",
            "15",
            "--FeatureMatching.use_gpu",
            "1",
        ]
        + extraMatchingFlags
    )
    profilerStage("Sequential Matching")

    print("Step 2b: Spatial matching...")
    subprocess.run(
        [
            "colmap",
            "spatial_matcher",
            "--database_path",
            db_path,
            "--SpatialMatching.max_num_neighbors",
            "20",
            "--SpatialMatching.max_distance",
            str(STAGE_SPATIAL_RADIUS),  # radius limit (5 meters)
            "--FeatureMatching.use_gpu",
            "1",
        ]
        + extraMatchingFlags
    )
    profilerStage("Spatial Matching")

    if STAGE_VOCABTREE:
        print("Step 2c: Vocab-tree matching...")
        subprocess.run(
            [
                "colmap",
                "vocab_tree_matcher",
                "--database_path",
                db_path,
                "--VocabTreeMatching.vocab_tree_path",
                VOCAB_TREE_PATH,
                "--VocabTreeMatching.num_images",
                str(STAGE_VOCABTREE_DEPTH),
                "--VocabTreeMatching.num_nearest_neighbors",
                "5",
                "--FeatureMatching.use_gpu",
                "1",
                "--TwoViewGeometry.min_num_inliers",
                "30",
            ]
            + extraMatchingFlags
        )
        profilerStage("VocabTree Matching")

    if EXPERIMENTAL_AR:
        print("Step 3a: Generating initial sparse model from AR priors...")
        with open(pfile("colmap/sparse/0/points3D.txt"), "w") as pf:
            pf.write("")
            pf.close()
        with open(pfile("colmap/sparse/0/cameras.txt"), "w") as pf:
            pf.write("")
            pf.close()

        print("Step 3b: Extracting camera intrinsics...")
        subprocess.run(
            [
                "/NERFSTUDIO/utils/_pix4d_mksparse",
                db_path,
                pfile("colmap/sparse/0"),
            ]
        )
        subprocess.run(
            [
                "colmap",
                "model_converter",
                "--input_path",
                pfile("colmap/sparse/0"),
                "--output_path",
                pfile("colmap/sparse/0"),
                "--output_type",
                "BIN",
            ]
        )
        subprocess.run(["sh", "-c", f"rm {pfile("colmap/sparse/0/*.txt")}"])
        profilerStage("AR Sparse Setup")

        print("Step 3c: Triangulating points...")
        subprocess.run(
            [
                "colmap",
                "point_triangulator",
                "--database_path",
                db_path,
                "--image_path",
                images_dir,
                "--input_path",
                pfile("colmap/sparse/0"),
                "--output_path",
                pfile("colmap/sparse/0"),
                "--Mapper.num_threads",
                "-1",
                "--Mapper.ba_use_gpu",
                "1",
                "--Mapper.ba_local_backend",
                EXPERIMENTAL_SOLVER_BACKEND,
                "--Mapper.ba_global_backend",
                EXPERIMENTAL_SOLVER_BACKEND,
                "--clear_points",
                "1",
                "--Mapper.tri_complete_max_reproj_error",
                str(AR_MAX_REPROJECTION_ERROR),
                "--Mapper.tri_merge_max_reproj_error",
                str(AR_MAX_REPROJECTION_ERROR),
            ]
        )

        profilerStage("AR Initial Triangulation")

        for loop in range(EXPERIMENTAL_AR_ITERS):
            print(
                f"Step 3di [{loop + 1}/{EXPERIMENTAL_AR_ITERS}]: Refining positions and rotations (Bundle Adjustment)..."
            )
            late_stage_feature = (
                "1"
                if (loop > ((EXPERIMENTAL_AR_ITERS // 2) - 1))
                and not HAS_CUSTOM_INTRINSICS
                else "0"
            )
            subprocess.run(
                [
                    "colmap",
                    "bundle_adjuster",
                    "--input_path",
                    pfile("colmap/sparse/0"),
                    "--output_path",
                    pfile("colmap/sparse/0"),
                    "--BundleAdjustment.refine_focal_length",
                    late_stage_feature,
                    "--BundleAdjustment.refine_principal_point",
                    "0",
                    "--BundleAdjustment.refine_extra_params",
                    late_stage_feature,
                    "--BundleAdjustment.refine_rig_from_world",
                    "1",
                    "--BundleAdjustment.refine_sensor_from_rig",
                    "1",
                    "--BundleAdjustment.refine_points3D",
                    "1",
                    "--BundleAdjustmentCeres.max_num_iterations",
                    str(SOLVER_ITERATION_CAP),
                    "--BundleAdjustmentCaspar.solver_iter_max",
                    str(SOLVER_ITERATION_CAP),
                    "--BundleAdjustment.backend",
                    EXPERIMENTAL_SOLVER_BACKEND,
                    "--BundleAdjustmentCeres.use_gpu",
                    "1",
                    "--BundleAdjustment.min_track_length",
                    "3",
                ]
            )

            if loop < EXPERIMENTAL_AR_ITERS - 1:
                curr_max_error = f"{(AR_MAX_REPROJECTION_ERROR / (loop + 1)):.2f}"
                print(
                    f"Step 3dii [{loop + 1}/{EXPERIMENTAL_AR_ITERS}]: Filtering outlier points (max reproj error: {curr_max_error}px)..."
                )
                quietRun(
                    [
                        "colmap",
                        "point_filtering",
                        "--input_path",
                        pfile("colmap/sparse/0"),
                        "--output_path",
                        pfile("colmap/sparse/0"),
                        "--max_reproj_error",
                        curr_max_error,
                        "--min_track_len",
                        "3",
                    ]
                )

                if EXPERIMENTAL_IMFILTER:
                    print(
                        f"Step 3dii-b [{loop + 1}/{EXPERIMENTAL_AR_ITERS}]: Filtering outlier images (max reproj error: {curr_max_error}px)..."
                    )
                    quietRun(
                        [
                            "colmap",
                            "image_filterer",
                            "--input_path",
                            pfile("colmap/sparse/0"),
                            "--output_path",
                            pfile("colmap/sparse/0"),
                            "--min_num_observations",
                            "10",
                            "--min_focal_length_ratio",
                            "0.1",
                            "--max_focal_length_ratio",
                            "10.0",
                        ]
                    )

                print(
                    f"Step 3diii [{loop + 1}/{EXPERIMENTAL_AR_ITERS}]: Re-triangulating points with optimized poses..."
                )
                subprocess.run(
                    [
                        "colmap",
                        "point_triangulator",
                        "--database_path",
                        db_path,
                        "--image_path",
                        images_dir,
                        "--input_path",
                        pfile("colmap/sparse/0"),
                        "--output_path",
                        pfile("colmap/sparse/0"),
                        "--Mapper.num_threads",
                        "-1",
                        "--Mapper.ba_use_gpu",
                        "1",
                        "--Mapper.ba_local_backend",
                        EXPERIMENTAL_SOLVER_BACKEND,
                        "--Mapper.ba_global_backend",
                        EXPERIMENTAL_SOLVER_BACKEND,
                        "--Mapper.tri_complete_max_reproj_error",
                        curr_max_error,
                        "--Mapper.tri_merge_max_reproj_error",
                        curr_max_error,
                    ]
                )
            profilerStage(f"AR Iteration {loop+1}")
    elif EXPERIMENTAL_GLOMAP:
        print("Step 3a: Calibrating view graph...")
        subprocess.run(["colmap", "view_graph_calibrator", "--database_path", db_path])
        profilerStage("View Graph Calibration")

        print("Step 3b: Global reconstruction...")
        GLOBAL_MAPPER_REFINE_OPTS = (
            [
                "--GlobalMapper.ba_refine_focal_length",
                "0",
                "--GlobalMapper.ba_refine_principal_point",
                "0",
                "--GlobalMapper.ba_refine_extra_params",
                "0",
            ]
            if HAS_CUSTOM_INTRINSICS
            else []
        )
        subprocess.run(
            [
                "colmap",
                "global_mapper",
                "--database_path",
                db_path,
                "--image_path",
                images_dir,
                "--output_path",
                pfile("colmap/sparse"),
                "--GlobalMapper.num_threads",
                "-1",
                "--GlobalMapper.track_min_num_views_per_track",
                "6",
                "--GlobalMapper.ba_ceres_use_gpu",
                "1",
                "--GlobalMapper.gp_use_gpu",
                "1",
                "--GlobalMapper.ba_backend",
                EXPERIMENTAL_SOLVER_BACKEND,
                "--GlobalMapper.ba_ceres_max_num_iterations",
                str(SOLVER_ITERATION_CAP),
            ]
        )
        profilerStage("Global Mapper")
    else:
        print("Step 3: Pose prior mapper...")
        POSE_MAPPER_REFINE_OPTS = (
            [
                "--Mapper.ba_refine_focal_length",
                "0",
                "--Mapper.ba_refine_principal_point",
                "0",
                "--Mapper.ba_refine_extra_params",
                "0",
            ]
            if HAS_CUSTOM_INTRINSICS
            else []
        )
        subprocess.run(
            [
                "colmap",
                "pose_prior_mapper",
                "--database_path",
                db_path,
                "--image_path",
                images_dir,
                "--output_path",
                pfile("colmap/sparse"),
                "--Mapper.num_threads",
                "-1",
                "--Mapper.filter_max_reproj_error",
                "1.5",
                "--Mapper.min_num_matches",
                "35",
                "--Mapper.max_reg_trials",
                "1",
                "--Mapper.ba_global_backend",
                "CERES",
                "--Mapper.ba_local_backend",
                "CERES",
                "--Mapper.ba_use_gpu",
                "1",
            ]
            + POSE_MAPPER_REFINE_OPTS
        )
        profilerStage("Pose Prior Mapper")

    print("Step 4a: Model alignment...")
    subprocess.run(
        [
            "colmap",
            "model_aligner",
            "--input_path",
            pfile("colmap/sparse/0"),
            "--output_path",
            pfile("colmap/sparse/0"),
            pfile("colmap/sparse/0"),
            pfile("colmap/sparse/0"),
            "--ref_images_path",
            priors_file,
            "--ref_is_gps",
            "0",
            "--alignment_type",
            "custom",
            # "--robust_alignment", "1",
            "--alignment_max_error",
            "1.5",
        ]
    )
    profilerStage("Model Alignment")

    print("Step 4b: Model orientation alignment...")
    subprocess.run(
        [
            "colmap",
            "model_orientation_aligner",
            "--input_path",
            pfile("colmap/sparse/0"),
            "--output_path",
            pfile("colmap/sparse/0"),
            "--image_path",
            images_dir,
            "--method",
            "IMAGE-ORIENTATION",
        ]
    )
    profilerStage("Model Orientation Alignment")

print("Shifting back to regular filesystem...")
quietRun(["mv", dest_path, true_dest_path])
profilerStage("Finalising")

print("")
print("[ PROJECT INFO ]")
print(f"Name: {projectMeta["name"]}")
print(f"Trigger Method: {projectMeta["trigger"]["triggerType"]}")
print(f"Distance Covered: {int(projectMeta["distanceTravelled"])}m")
print(f"Frame Count: {projectMeta["initial_image_count"]} images")
print(
    f"Coordinate Space: {projectMeta["locationInformation"]["coordinateSystem"]["name"]}"
)
print("")
print("[ RECONSTRUCTION INFO ]")
if len(sys.argv) > 3:
    print("Flags: ")
    flags = sys.argv[3].lower().strip().split(",")
    for flag in flags:
        print(f"  > {flag}")
else:
    print("Flags: None")

total_duration = times[-1]["stamp"] - init_time
max_stage_name_len = max(len(t["name"]) for t in times)
print("Profiler: ")
for timed_stage in times:
    stage_name = timed_stage["name"]
    duration_secs = timed_stage["time"]
    total_secs = round(duration_secs)
    if total_secs == 0:
        time_str = f"{duration_secs:.2f}s" if duration_secs > 0 else "0s"
    else:
        hours = total_secs // 3600
        minutes = (total_secs % 3600) // 60
        secs = total_secs % 60

        parts = []
        if hours > 0:
            parts.append(f"{hours}h")
        if minutes > 0:
            parts.append(f"{minutes}m")
        if secs > 0:
            parts.append(f"{secs}s")
        time_str = " ".join(parts)
    pct = (duration_secs / total_duration) * 100
    print(f"{stage_name:<{max_stage_name_len}} {time_str:<12} {pct:.1f}%")


print(f"Completed in {int(time.time() - start_time)}s")
