#!/bin/sh
if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Turn a video into mapped images using COLMAP + GLOMAP + ALIKED + LIGHTGLUE."
  echo "Usage: $0 <video_file> <output_dir> [min_sharpness(=1000)] [ns-process-data flags]"
  echo "For example: $0 vid/basic_scan.mp4 experiment/ 1200 --num-frames-target 1000 --verbose"
  exit 1
fi

if [ ! -f /NERFSTUDIO/weights/aliked-lightglue.onnx ]; then
  echo "Run zx_download_assets onnx first"
  exit
fi

rm -rf /fast/*
mkdir -p /fast

FN=$(realpath $1)
TRUE_DN=$(realpath $2)
if [ -d "$TRUE_DN" ]; then
    rm -r "$TRUE_DN"
fi
DN=/fast/$TRUE_DN
MINIMUM_SHARPNESS=${3:-1000}
shift 3
export QT_QPA_PLATFORM=offscreen
echo "Using video file: "$FN
echo "Writing to output dir: "$DN

mkdir -p $DN

sleep 3

echo "Running Nerfstudio frame extraction..."
ns-process-data video --gpu --data $FN --output-dir $DN --skip-colmap "$@" #--num-frames-target 650

find "$DN/images/" -type f -name "*.png" -print0 | \
    xargs -0 -n 100 -P $(nproc) zx_find_blurry.py $MINIMUM_SHARPNESS > $DN/__blurry_files.txt

for filepath in $(cat $DN/__blurry_files.txt); do
    filename=$(basename "$filepath")
    echo "Purging $filename..."
    rm -f $DN/images*/$filename
done

#rm $DN/__blurry_files.txt

START_TIME=$(date +%s)
echo "Creating COLMAP v4 database + extracting features..."
mkdir -p $DN/colmap
colmap feature_extractor \
  --database_path $DN/colmap/database.db \
  --image_path $DN/images \
  --FeatureExtraction.use_gpu 1 \
  --ImageReader.single_camera 1 \
  --ImageReader.camera_model OPENCV \
  --FeatureExtraction.type ALIKED_N16ROT \
  --FeatureExtraction.num_threads $(($(nproc) - 2))  \
  --AlikedExtraction.n16rot_model_path "/NERFSTUDIO/weights/aliked-n16rot.onnx"
# Switch between OPENCV / SIMPLE_RADIAL as cam model if things start breaking

echo "Matching features sequentially..."

colmap sequential_matcher \
  --database_path $DN/colmap/database.db \
  --FeatureMatching.use_gpu 1 \
  --FeatureMatching.type ALIKED_LIGHTGLUE \
  --FeatureMatching.num_threads $(($(nproc) - 2)) \
  --SequentialMatching.overlap 22 \
  --AlikedMatching.lightglue_model_path "/NERFSTUDIO/weights/aliked-lightglue.onnx"

echo "Vocab-treeing..."

colmap vocab_tree_matcher \
  --database_path $DN/colmap/database.db \
  --FeatureMatching.num_threads $(($(nproc) - 2)) \
  --VocabTreeMatching.vocab_tree_path /NERFSTUDIO/weights/vocab_tree_faiss_flickr100K_words64K_aliked_n16rot.bin \
  --VocabTreeMatching.num_images 50 \
  --VocabTreeMatching.num_nearest_neighbors 5 \
  --FeatureMatching.use_gpu 1 \
  --FeatureMatching.type ALIKED_LIGHTGLUE \
  --TwoViewGeometry.min_num_inliers 30 \
  --AlikedMatching.lightglue_model_path "/NERFSTUDIO/weights/aliked-lightglue.onnx"

echo "Calibrating database..."
cp $DN/colmap/database.db $DN/colmap/database_calibrated.db
colmap view_graph_calibrator \
  --database_path $DN/colmap/database_calibrated.db

mkdir -p $DN/colmap/sparse

echo "Using GLOMAP for reconstruction..."
colmap global_mapper \
  --database_path $DN/colmap/database_calibrated.db \
  --image_path $DN/images \
  --GlobalMapper.track_min_num_views_per_track 6 \
  --output_path $DN/colmap/sparse \
  --GlobalMapper.num_threads $(($(nproc) - 2))

DURATION=$(( ( $(date +%s) - $START_TIME ) / 60 ))

echo "Shifting back to regular filesystem..."
mv $DN $TRUE_DN

echo Done in $DURATION minutes!

exit 0