#!/bin/sh
if ( [ -z "$1" ] || [ -z "$2" ] ) && [ "$1" != "--extraflags" ]; then
  echo "Turn a 360 panoramic video into mapped images using a patched panorama_sfm.py script."
  echo "Raw outputs are saved in subdirectory 'three-sixty', for other purposes just use experiments/ directly"
  echo "Input videos must have a 2:1 aspect ratio, and be equirectangular panoramas"
  echo "Usage: $0 <video_file> <output_dir> [frame_extract_stepping] [extra flags]"
  echo "Or: $0 --extraflags to see extra flags"
  echo ""
  exit 1
fi



SCRIPT_PATH=$(which panorama_sfm_patched.py)

if [ -f ./panorama_sfm_patched.py ]; then
  SCRIPT_PATH=$(realpath ./panorama_sfm_patched.py)
fi

if [ "$1" = "--extraflags" ]; then
  $SCRIPT_PATH --help
  exit 1
fi

FN=$(realpath $1)
DN=$(realpath $2)
NFRAMES=${3:-2}
BONUSFLAGS=${4:-""}

if [ -d "$DN/three-sixty" ]; then
    rm -r "$DN"
fi


export QT_QPA_PLATFORM=offscreen

echo "Using video file: "$FN
echo "Writing to output dir: "$DN
echo "Using every n="$NFRAMES" for SfM"

sleep 3
mkdir -p $DN
mkdir -p $DN/preframes

MADE_SYMLINK="0"

if [ ! -f ./vocab_tree_faiss_flickr100K_words32K.bin ]; then
  if [ ! -f /NERFSTUDIO/weights/vocab_tree_faiss_flickr100K_words32K.bin ] && [ ! -f ./vocab.bin ]; then
    echo "Run 'zx_download_assets small' to download the 32k vocab tree. To use a different vocab tree, create a vocab.bin in the current working directory."
    exit
  fi
  if [ -f ./vocab.bin ]; then
    ln -s $(realpath ./vocab.bin) ./vocab_tree_faiss_flickr100K_words32K.bin
    MADE_SYMLINK="1"
  else
    if [ -f /NERFSTUDIO/weights/vocab_tree_faiss_flickr100K_words32K.bin ]; then
      ln -s /NERFSTUDIO/weights/vocab_tree_faiss_flickr100K_words32K.bin ./vocab_tree_faiss_flickr100K_words32K.bin
      MADE_SYMLINK="1"
    fi
  fi
else
  echo "PyCOLMAP is hardcoded to use vocab_tree_faiss_flickr100K_words32K.bin by default if it exists. Move the file to a different directory or rename it to use a different vocab tree."
fi

ffmpeg -i $FN -vf "select=not(mod(n\,$NFRAMES))" -fps_mode vfr "$DN/preframes/frame_%05d.png"

mkdir -p $DN/three-sixty
#/NERFSTUDIO/weights/vocab_tree_faiss_flickr100K_words32K.bin

echo "Doing 360 SfM using $SCRIPT_PATH"

$SCRIPT_PATH \
    --input_image_path $DN/preframes/ \
    --output_path $DN/three-sixty/ \
    $BONUSFLAGS

ln -s $DN/three-sixty/ $DN/colmap
ln -s $DN/three-sixty/images/ $DN/images

if [ "$MADE_SYMLINK" -eq "1" ]; then
  unlink ./vocab_tree_faiss_flickr100K_words32K.bin
fi

rm $DN/preframes/*
echo "Individual frames removed to save storage space." > $DN/preframes/NOTICE.txt

echo "Outputs are saved in subdirectory 'three-sixty'"
