#!/bin/sh
if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Example script to splat mapped frames using nerfstudio's splatfacto. I recommend not using these settings."
  echo "Usage: $0 <mapped data dir> <splat dir> [downscale_factor] [extra pipeline flags]"
  echo "";
  echo "Set env var FORCE_SCALE to a number to force a specific model scale. eg: FORCE_SCALE=0.2"
  echo "Set env var FORCE_MODEL to a number to force a specific model. eg: FORCE_MODEL=splatfacto-big"
  echo "Useful extra flags: "
  echo " --pipeline.model.cull-alpha-thresh 0.1"
  echo " --pipeline.model.strategy mcmc"
  exit 1
fi

DOWNSCALE=${3:-1}
DSFLAG="--pipeline.model.num-downscales 0"
if [ "$DOWNSCALE" != "1" ]; then
  DSFLAG=""
fi

mkdir -p $2
P_1=$(realpath $1)
P_2=$(realpath $2)

if [ -z "$3" ]; then
  shift 2
else
  shift 3
fi

SCALING_FLAGS=""
if [ ! -z "$FORCE_SCALE" ]; then
  echo "Forcing import scale of: $FORCE_SCALE"
  SCALING_FLAGS="--auto-scale-poses False --scale-factor $FORCE_SCALE"
fi

MODEL="splatfacto"
if [ ! -z "$FORCE_MODEL" ]; then
  MODEL="$FORCE_MODEL"
fi
echo "Using model: $MODEL"
sleep 1
ns-train $MODEL --output-dir $(realpath $P_2) \
    --pipeline.model.use_bilateral_grid True \
    --pipeline.model.sh-degree 2 \
    --pipeline.model.use-scale-regularization True \
    $DSFLAG "$@" \
    --data $(realpath $P_1) colmap --orientation-method none --center-method poses $SCALING_FLAGS \
        --downscale-factor $DOWNSCALE